# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  node:
    cmds:
      - anvil --fork-url {{.NODE_URL}}

  test:
    vars:
      file: '{{.file}}'
    cmds:
      - forge test -vvvvv --mp {{.file}} --fork-url {{.RPC_URL}}

  testYeStake:
    cmds:
      - task: test
        vars:
          file: test/YeStake.t.sol